### ISSUE TITLE
flask-starter bundle not working

### ISSUE THREAD

**Issue by rbetancor** [akveo/ngx-admin-bundle-support#12]
After buying the flask-starter bundle, been unable to launch the front-end part.

After npm install without issues, the normal warnings about audit, but when try to launch npm start, got lot of messages like this one:

 67% building 1963/2055 modules 92 active ...nel/charts/charts-common.component.scssWARNING: Nebular Theme: `nb-theme()` cannot find value for key `color-danger` for theme `default`
         on line 59 of node_modules/@nebular/theme/styles/core/theming/_get-value.scss, in function `nb-theme`
         from line 10 of stdin, in mixin `@content`
         from line 116 of node_modules/@nebular/theme/styles/core/theming/_install.scss, in mixin `@content`
         from line 97 of node_modules/@nebular/theme/styles/core/theming/_install.scss, in mixin `nb-install-component-with-scss-vars`
         from line 115 of node_modules/@nebular/theme/styles/core/theming/_install.scss, in mixin `nb-install-component`
         from line 8 of stdin

That kind of block of messages get repeating and repeating for lot of the different values, like progress-bar-background, progress-bar-warning-background, color-fg-heading, separator ... for all the themes, default, corporate, etc.

It get stuck on the npm start for a very long time, before giving a final error and not staring the front-end.

May someone point me to the right direction to fix this?.

**Comment by rbetancor** [comment]
Solved the non-starting issue, doing:

npm cache clean --force
rm -rf node_modules
rm packages-lock.json

and giving more RAM to the VM I use for develop, seems that the newer versions of Node.JS eats more RAM than previous ones, I was getting a errno 137, that now have dissapear.

But the warkings about the "missing values for key" are still there, Any clue how to fix them?

**Comment by valentinkononov** [comment]
Hi @rbetancor thanks for the issue, warnings will be fixed in the nearest update of a bundle!
