### ISSUE TITLE
Wrong endpoint

### ISSUE THREAD

**Issue by sim19k** [akveo/ngx-admin-bundle-support#13]
Sry, don't understand how this project can work..the Rest service url for the authentication is wrong.

Example:

**Angular call:**
Request URL: http://localhost:3001/api/auth/login

**Java endPoint:**

    @Controller
    @RequestMapping("/auth")

    /**
     * Login user
     * @param loginDTO user credentials
     * @return generated token
     */
    @PostMapping("/login")
    public ResponseEntity login(@Valid @RequestBody LoginDTO loginDTO) {
        Token token = authService.login(loginDTO);
        return toResponse(token);
    }

the endpoint is different, the port too...

This is easily configurable and fixable, but the documentation don't say nothing about this.

Thank you

**Comment by valentinkononov** [comment]
Hi! We have several different backends, and that's why at the moment there it's needed to correct url to API in environment.ts and environment.prod.ts. As for documentation, thanks for mentioning this, I will correct it.
