### ISSUE TITLE
More information about the samples

### ISSUE THREAD

**Issue by jonDel** [akveo/ngx-admin-bundle-support#4]
There are little to none information about these code samples. Are they pieces of the bundle code? How am I supposed to use them for testing?  Could someone provide some documentation about the samples?

**Comment by valentinkononov** [comment]
Provided code samples are not supposed to be used for testing, the main idea is to demonstrate the overall level of code at backend sides, what you can expect when buy a particular bundle. 

As for documentation - we are working on the new interactive portal for demonstration and documentation for existing bundles. Right now we provide running instructions for each bundle as part of the code package.
