### ISSUE TITLE
Can not start NodeJS MongoDB Starter bundle

### ISSUE THREAD

**Issue by daveboulden** [akveo/ngx-admin-bundle-support#7]
Having followed the instructions in the enclosed INSTRUCTION.pdf file to start the back-end, I successfully ran the `npm install` command and edited the MongoDB connection string in `config/default.js` to connect to a working MongoDB server.

Upon issuing `npm start`, it produced the error:

'npm ERR! missing script: start'

Indeed there is no entry in the scripts node of `package.json` for a start script and none of the other scripts run without errors either. The PDF also refers to Angular 7.0.3, so I am wondering, is the the right PDF to go with the newest release of this bundle?

What do I need to get the unaltered bundle back-end running?

**Comment by daveboulden** [comment]
I had to fix this one myself by adding a start script reference to  `package.json`:
```
{
    "name": "bundle-node",
    "version": "1.0.0",
    "main": "index.js",
    "scripts": {
        "start": "node ./src/app",
        "start-starter": "node ./src/app",
        "start-ecom": "node ./src/app.ecom",
        "start-full": "node ./src/app.full",
        "dev": "./node_modules/nodemon/bin/nodemon.js ./src/app",
        "start:prod": "export NODE_ENV=production&&node ./src/app",
        "lint": "eslint --report-unused-disable-directives .",
        "lint:fix": "eslint --fix ."
    },
```
You either need to update your bundle to have a valid start script reference or replace the outdated instructions documentation to explain what I believe was your intention that the user should edit `package.json` and copy one of the mis-named start script references to use for the  particular bundle they have, otherwise it is just plain confusing when the documentation doesn't match the code.

**Comment by valentinkononov** [comment]
Hi Dave! Thanks for mentioning this. Both package.json and doc will be updated soon. I'm glad you manage to fix it for yourself, I will update build ASAP.

**Comment by valentinkononov** [comment]
fixed. Also I fixed users/current call, which returned empty user for some occasions

**Comment by daveboulden** [comment]
Would it be possible to get a list of the files that have changed with each release? I have found this time round I have had to run a visual difference application across all the files and subfolders to and examine each file that reported a difference see which items are new. I cannot simply copy it all over in one go as I have my own new code added into some of these files.

Regards,
Dave

**Comment by valentinkononov** [comment]
oh yeah, I have this in mind too, update as is now is a bit complicated. I added Change Log page - https://store.akveo.com/pages/change-log 

Do you think having a list of changed files will solve this issue? Or something more convenient might be needed

**Comment by daveboulden** [comment]
The change log page is very useful to have.

Initially, a simple list of the files that have actually been changed would save me a lot of time when updating to the latest bundle version. Something more convenient would be great, but I’m not sure what that would be. Have you seen any examples of tools other developers use when releasing new package updates?

Regards,
Dave.
